config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'recipes/get_category_children' => 'recipes#get_category_children', defaults: { format: 'json' } #Ajaxで動くアクションのルートを作成
  get 'shopping/get_category_children' => 'shopping#get_category_children', defaults: { format: 'json' } #Ajaxで動くアクションのルートを作成

  get "/" => "home#index"
  get "/about" => "home#about"
  get "/unauthenticated" => "home#unauthenticated"
  #アカウント
  get "users/login_form" => "user#login_form" 
  post "users/login" => "user#login" 
  get "users/new_account" => "user#new_account" 
  post "users/create_account" => "user#create_account"
  post "users/logout" => "user#logout"
  get "users/:id" => "user#show"
  delete "users/delete" => "user#destroy_account"
  get "users/:id/edit" => "user#edit_account"
  post "/update_account" => "user#update_account"
  #レシピ機能
  get "recipes/recipe_top" => "recipes#recipe_top" #レシピ一覧
  get "recipes/recipe_search" => "recipes#search_recipe" #レシピ検索
  get "recipes/recipe_new" => "recipes#recipe_new" #レシピ登録ページ
  post "recipes/create_recipe" => "recipes#create_recipe" #レシピ登録
  get "recipes/show_food_choices/:id" => "recipes#show_food_choices" #材料リストの設定(自動検索)
  get "recipes/show_food_choices_by_category/" => "recipes#show_food_choices_by_category" #材料リストの追加設定（手動）
  post "recipes/create_materials" => "recipes#create_materials" #材料リストの登録
  post "recipes/create_manual_materials" => "recipes#create_manual_materials" #材料リストの追加登録
  get "recipes/:id" => "recipes#show" #レシピと材料リストの詳細
  delete "recipes/:id/delete" => "recipes#destroy_recipe" #レシピ削除
  get "recipes/:id/edit_recipe" => "recipes#edit_recipe" #レシピ編集
  post "recipes/:id/update_recipe" => "recipes#update_recipe" #レシピ更新
  delete "recipes/material/:id/delete" => "recipes#destroy_material" #材料リストの削除
  get "recipes/:id/edit_material" => "recipes#edit_material" #材料リストの編集
  post "recipes/:id/update_material" => "recipes#update_material" #材料リストの更新
  #献立機能
  get "meal/menu_top" => "meal#menu_top" #献立表示
  get "meal/menu_new" => "meal#menu_new" #献立決め
  get "meal/menu_search" => "meal#menu_search" #献立用レシピ検索
  post "meal/menu_select" => "meal#menu_select" #献立用レシピ選択
  delete "meal/menu_delete" => "meal#destroy_menu" #献立削除
  #買い物リスト
  get "shopping/shopping_top" => "shopping#shopping_top" #買い物リスト
  post "shopping/search_shopping" => "shopping#search_shopping" #買い物リストの期間を指定する
  get "shopping/create_shopping_list" => "shopping#create_shopping_list" #買い物リスト作成画面
  post "shopping/sum_shopping_list" => "shopping#sum_shopping_list" #買い物リストの作成
  delete "shopping/list/delete" => "shopping#destroy" #買い物リストの削除
  get "shopping/show_shopping_list" => "shopping#show_shopping_list"#買い物リストを表示画面
  get "edit_shopping_list" => "shopping#edit_shopping_list" #買い物リスト編集画面
  post "update_shopping_list" => "shopping#update_shopping_list" #買い物リスト変更
  post "add_shopping" => "shopping#add_shopping"  #買い物リストの追加
  delete "shopping/:id/delete" => "shopping#destroy_shopping" #買い物リストの項目削除
  get "create_csv" => "shopping#create_csv" #買い物リストのCSVを作成
  
end

app/models/meal.rb
class Meal < ApplicationRecord
    validates :start_date ,presence: true
    def start_time
        self.start_date
    end
end

app/controllers/meal_controller.rb
require'date'
class MealController < ApplicationController
    before_action :set_recipe

    def menu_top 
    end

    def menu_new
        @results = @search_recipes.result
    end

    def menu_search
        @results = @search_recipes.result
        render("meal/menu_new")
    end

    def menu_select 
        @new_menu = Meal.new(
            start_date: params[:start_date],
            recipe_id: params[:recipe_id]
        )
        if @new_menu.save
            flash[:notice] = "メニューを登録しました"
            redirect_to("/meal/menu_new")
       else
            flash[:new_menu_error] = "日付選択されていません。日付を選択してください。"
            redirect_to("/meal/menu_new")
       end
    end

    def destroy_menu
        destroyed_menu = Meal.find_by(id: params[:id]).destroy
        if destroyed_menu
            flash[:notice] = "#{destroyed_menu.start_date}のメニュー【#{Recipe.find_by(id:destroyed_menu.recipe_id).name}】を削除しました"
            redirect_to("/meal/menu_new")
        end
    end
    
    private

    def set_recipe
        @search_recipes = Recipe.ransack(params[:q]) 
        @menus = Meal.all  
    end

end

app/helpers/meal_helper.rb
module MealHelper
end

app/views/meal/menu_new.html.erb
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Menutable |menu|</title>
</head>
<body>
    <div class="input_table_2">
        <div class="input_table_title">献立作成<%= link_to meal_menu_top_path ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
        <div class="main_contents">
            <div class="search_and_registration_form">
                <!--検索-->
                <%= search_form_for @search_recipes, url:"/meal/menu_search" ,class:"recipe_search" do |f| %>
                    <%= f.search_field :name_cont ,size:30,class:"recipe_search_field"%>
                    <%= f.button :type => "submit",class:"search_btn" do %><i class="fas fa-search"></i><% end %>
                <% end %>
                <div class="form-error"><%= flash[:new_menu_error]%></div>
                <% if @results %>
                    <table class="menu_select">
                        <tr>
                            <th>レシピ名</th>
                            <th>日付</th>
                            <th>　　</th>
                        </tr>
                        <% @results.each do |r|%>
                            <tr>
                                <!--登録-->
                                <%= form_with url:"/meal/menu_select" do |f| %>
                                    <td class='recipe_name'>
                                        <%= f.hidden_field :recipe_id, value: r.id %>
                                        <%= link_to r.name,"/recipes/#{r.id}" %>
                                    </td>
                                    <td>
                                        <%= f.date_field :start_date,class:"select_date"%>
                                    </td>
                                    <td>
                                        <%= f.button type:"submit",class:"create_new" do %><i class="fas fa-plus-circle"></i><% end %>
                                    </td>
                                <% end %>
                            </tr>
                        <% end %>
                        </tr>
                    </table>
                <%else%>
                    <div class="how_to_register">
                        <p>レシピを検索し、登録日を選んでから追加ボタンを押してください。<br>献立の削除する場合はカレンダー上のレシピ名をクリックしてください。</p>
                    </div>
                <%end%>
            </div>
            <div class="determined_calendar">
                <!--献立カレンダー-->
                    <div class="calender_title"><i class="fas fa-utensils"></i>　登録済みの献立</div>
                    <div class="edit_menu_calender">
                        <%= week_calendar number_of_weeks:2 ,events:@menus do |date,menus| %>
                            <%= date.day %>
                            <% menus.each do |m| %>
                                <div>
                                    <li><%= link_to Recipe.find_by(id:m.recipe_id).name,meal_menu_delete_path(id:m.id),method: :delete, data: { confirm: "献立を削除してよろしいですか?"}  %></li>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/meal/menu_top.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Make a menu</title>
</head>
<body>
  <header>
      <div class="title_logo">Menutable</div>
        <div class="account_list">
          <%= link_to "/users/#{@current_user.id}",class:'header_link',method: :get do %>
            <i class="fas fa-user"></i> <%=@current_user.login_id%>
          <%end%>
          <%= link_to "/users/logout",class:'header_link',method: :post, data: {confirm: "ログアウトしますか？"} do %>
            <i class="fas fa-sign-out-alt"></i> Logout
          <%end%>
        </div>
        <div class="menu_list">
          <%= link_to "/about",class:'header_link',method: :get do %>
            <i class="fas fa-home"></i> About
          <%end%>
          <%= link_to "/recipes/recipe_top",class:'header_link',method: :get do %>
            <i class="fas fa-book"></i> Recipe
          <%end%>
          <%= link_to "/meal/menu_top",class:'header_link',method: :get do %>
            <i class="far fa-calendar-alt"></i> Menu
          <%end%>
          <%= link_to "/shopping/shopping_top",class:'header_link',method: :get do %>
            <i class="far fa-list-alt"></i> Shopping
          <%end%>
          <%= link_to 'https://www.iy-net.jp/',target: :_blank, rel: "noopener noreferrer",class:'header_link',method: :get do %>
            <i class="fas fa-shopping-cart"></i> Store
          <%end%>
        </div>
  </header>
  <main>
    <div class="auto">
      <% if flash[:notice] %>
        <div class="flash"><%= flash[:notice] %></div>
      <%end%>
    </div>
    <nav>
        <div class="nav_title">Menu</div>
        <div class="nav_menu">
            <li><%= link_to "献立作成・編集","/meal/menu_new",class:"nav_menu_link" %></li>
        </div>
    </nav>
    <article>
      <!--献立カレンダー-->
      <div class="menu_sub_title"><i class="far fa-calendar-alt"></i>  Calendar</div>
          <div class="menu_calender">
              <%= week_calendar number_of_weeks:4 ,events:@menus do |date,menus| %>
                  <%= date.day %>
                  <% menus.each do |m| %>
                      <li><%= link_to Recipe.find_by(id:m.recipe_id).name ,Recipe.find_by(id:m.recipe_id).address ,class:"calender_recipe_link" %></li>
                  <% end %>
              <% end %>
          </div>
          <br>
          <br>
    </article>
  </main>
</body>
</html>

app/views/meal/new.html.erb
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application','data-turbolinks-track': 'reload'%>
    <title>NEW menu</title>
</head>
<body>
    <div class="input_table_2">
        <div class="input_table_title">Menu<%= link_to menu_index_path ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
        <div class="main_contents">
            <div class="search_and_registration_form">
                <!--検索-->
                <%= search_form_for @search_recipes, url:"/menu/search" ,class:"recipe_search" do |f| %>
                    <%= f.search_field :name_cont ,size:30,class:"recipe_search_field"%>
                    <%= f.button :type => "submit",class:"search_btn" do %><i class="fas fa-search"></i><% end %>
                <% end %>
                <div class="form-error"><%= flash[:new_menu_error]%></div>
                <% if @results %>
                    <table class="menu_select">
                        <tr>
                            <th>レシピ名</th>
                            <th>日付</th>
                            <th>　　</th>
                        </tr>
                        <% @results.each do |r|%>
                            <tr>
                                <!--登録-->
                                <%= form_with url:"/menu/select" do |f| %>
                                    <td class='recipe_name'>
                                        <%= f.hidden_field :recipe_id, value: r.id %>
                                        <%= link_to r.name,"/recipes/#{r.id}" %>
                                    </td>
                                    <td>
                                        <%= f.date_field :start_date,class:"select_date"%>
                                    </td>
                                    <td>
                                        <%= f.button type:"submit",class:"create_new" do %><i class="fas fa-plus-circle"></i><% end %>
                                    </td>
                                <% end %>
                            </tr>
                        <% end %>
                        </tr>
                    </table>
                <%else%>
                    <div class="how_to_register">
                        <p>レシピを検索し、登録日を選んでから追加ボタンを押してください。<br>献立の削除する場合はカレンダー上のレシピ名をクリックしてください。</p>
                    </div>
                <%end%>
            </div>
            <div class="determined_calendar">
                <!--献立カレンダー-->
                    <div class="calender_title"><i class="fas fa-utensils"></i>　登録済みの献立</div>
                    <div class="edit_menu_calender">
                        <%= week_calendar number_of_weeks:1 ,events:@menus do |date,menus| %>
                            <%= date.day %>
                            <% menus.each do |m| %>
                                <div>
                                    <li><%= link_to Recipe.find_by(id:m.recipe_id).name,menu_delete_path(id:m.id),method: :delete, data: { confirm: "献立を削除してよろしいですか?"}  %></li>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>