config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'recipes/get_category_children' => 'recipes#get_category_children', defaults: { format: 'json' } #Ajaxで動くアクションのルートを作成
  get 'shopping/get_category_children' => 'shopping#get_category_children', defaults: { format: 'json' } #Ajaxで動くアクションのルートを作成

  get "/" => "home#index"
  get "/about" => "home#about"
  get "/unauthenticated" => "home#unauthenticated"
  #アカウント
  get "users/login_form" => "user#login_form" 
  post "users/login" => "user#login" 
  get "users/new_account" => "user#new_account" 
  post "users/create_account" => "user#create_account"
  post "users/logout" => "user#logout"
  get "users/:id" => "user#show"
  delete "users/delete" => "user#destroy_account"
  get "users/:id/edit" => "user#edit_account"
  post "/update_account" => "user#update_account"
  #レシピ機能
  get "recipes/recipe_top" => "recipes#recipe_top" #レシピ一覧
  get "recipes/recipe_search" => "recipes#search_recipe" #レシピ検索
  get "recipes/recipe_new" => "recipes#recipe_new" #レシピ登録ページ
  post "recipes/create_recipe" => "recipes#create_recipe" #レシピ登録
  get "recipes/show_food_choices/:id" => "recipes#show_food_choices" #材料リストの設定(自動検索)
  get "recipes/show_food_choices_by_category/" => "recipes#show_food_choices_by_category" #材料リストの追加設定（手動）
  post "recipes/create_materials" => "recipes#create_materials" #材料リストの登録
  post "recipes/create_manual_materials" => "recipes#create_manual_materials" #材料リストの追加登録
  get "recipes/:id" => "recipes#show" #レシピと材料リストの詳細
  delete "recipes/:id/delete" => "recipes#destroy_recipe" #レシピ削除
  get "recipes/:id/edit_recipe" => "recipes#edit_recipe" #レシピ編集
  post "recipes/:id/update_recipe" => "recipes#update_recipe" #レシピ更新
  delete "recipes/material/:id/delete" => "recipes#destroy_material" #材料リストの削除
  get "recipes/:id/edit_material" => "recipes#edit_material" #材料リストの編集
  post "recipes/:id/update_material" => "recipes#update_material" #材料リストの更新
  #献立機能
  get "meal/menu_top" => "meal#menu_top" #献立表示
  get "meal/menu_new" => "meal#menu_new" #献立決め
  get "meal/menu_search" => "meal#menu_search" #献立用レシピ検索
  post "meal/menu_select" => "meal#menu_select" #献立用レシピ選択
  delete "meal/menu_delete" => "meal#destroy_menu" #献立削除
  #買い物リスト
  get "shopping/shopping_top" => "shopping#shopping_top" #買い物リスト
  post "shopping/search_shopping" => "shopping#search_shopping" #買い物リストの期間を指定する
  get "shopping/create_shopping_list" => "shopping#create_shopping_list" #買い物リスト作成画面
  post "shopping/sum_shopping_list" => "shopping#sum_shopping_list" #買い物リストの作成
  delete "shopping/list/delete" => "shopping#destroy" #買い物リストの削除
  get "shopping/show_shopping_list" => "shopping#show_shopping_list"#買い物リストを表示画面
  get "edit_shopping_list" => "shopping#edit_shopping_list" #買い物リスト編集画面
  post "update_shopping_list" => "shopping#update_shopping_list" #買い物リスト変更
  post "add_shopping" => "shopping#add_shopping"  #買い物リストの追加
  delete "shopping/:id/delete" => "shopping#destroy_shopping" #買い物リストの項目削除
  get "create_csv" => "shopping#create_csv" #買い物リストのCSVを作成
  
end

app/models/shopping.rb
class Shopping < ApplicationRecord
    validates :start_date, presence: true
    validates :end_date, presence: true
end

app/controllers/shopping_controller.rb
require'date'
require 'csv'
require_relative "converter.rb"
class ShoppingController < ApplicationController
include Converter

    def shopping_top 
        @menus = Meal.all
    end

    def create_shopping_list
        @menus = Meal.all
    end

    def sum_shopping_list
        if params[:start_date].empty? || params[:start_date2].empty?
            flash[:error_new_shopping] = "必ず２つ、日付を選択してください。"
            redirect_to shopping_create_shopping_list_path
        else
            menu=Meal.where(start_date:params[:start_date]..params[:start_date2])
            menu_recipe_id = []
                menu.each do |m|
                    menu_recipe_id << m.recipe_id
                end 
            menu_recipe_id

            material_list = Material.where(recipe_id:menu_recipe_id)
            @materials = material_list.group_by{|i| i.food_id}.select{|k,v| v.one?}.keys 
            @duplicate_materials = material_list.group_by{|i| i.food_id}.reject{|k,v| v.one?}.keys #重複している食材のfood_idの配列
            @materials.each do |i_id|
                Material.where(recipe_id:menu_recipe_id,food_id:i_id).each do |material|
                    shopping_item= Shopping.new(
                        start_date: params[:start_date],
                        end_date: params[:start_date2],
                        food_id: i_id,
                        quantity: material.quantity ,
                        unit: Food.find_by(id:i_id)[:unit]
                        )
                    shopping_item.save
                end
            end    
            if @duplicate_materials
                @duplicate_materials.each do |duplicate|
                    quantities=Material.where(recipe_id:menu_recipe_id,food_id:duplicate).pluck(:quantity)
                        unless quantities.include?(nil)
                            sum_quantity = quantities.sum #分量の合計
                        else
                            sum_quantity = 0
                        end
                    
                        if Food.find_by(id:duplicate)[:unit] === "none"
                            item_unit = nil
                        else
                            item_unit = Food.find_by(id:duplicate)[:unit]
                        end
                    duplicate_shopping_item = Shopping.new(
                        start_date: params[:start_date],
                        end_date: params[:start_date2],
                        food_id: duplicate,
                        quantity:  sum_quantity,
                        unit: Food.find_by(id:duplicate)[:unit]
                        )
                    duplicate_shopping_item.save
                end
            end
            flash[:notice]="#{params[:start_date]}~#{params[:start_date2]}の買い物リストを作成しました"
            redirect_to shopping_show_shopping_list_path(start_date:params[:start_date],end_date:params[:start_date2])
        end
    
    end

    def show_shopping_list
        
    end

    def search_shopping
        if params[:start_date].empty? || params[:end_date].empty? 
            flash[:error_view] = "日付を選択してください"
            redirect_to shopping_shopping_top_path
        else
            search_list = Shopping.where(start_date:params[:start_date]).where(end_date:params[:end_date])
            if search_list.empty?
                flash[:error_view] = "買い物リストが存在しません。再度確認して日付を入力してください。"
                redirect_to shopping_shopping_top_path
            else
                redirect_to shopping_show_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date])
            end    
        end
    end

    def edit_shopping_list
        @category_parent_array = ["--category--"]
        #データベースから、親カテゴリーのみ抽出し、配列化
            Food.where(unit:nil).each do |parent|
            @category_parent_array << parent.name
            end
    end

    def get_category_children
        #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
        @category_children = Food.find_by(name: params[:category]).children
    end

    def update_shopping_list
        @edit_shopping =Shopping.find_by(id: params[:id])
        @edit_shopping.quantity = params[:quantity]
        if  params[:quantity].empty?
            flash[:error_edit_shopping]="数量が空欄です。入力してください。"
            redirect_to shopping_edit_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date])
        else
            @edit_shopping.save
            flash[:notice]= "#{Food.find_by(id:@edit_shopping.food_id)[:name]}の数量を変更しました"
            redirect_to shopping_edit_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date])
        end
    end

    def destroy
        destroy_shoppinglist = Shopping.where(start_date:params[:start_date]).where(end_date:params[:end_date]).destroy_all
        if destroy_shoppinglist
            flash[:notice] = "【#{params[:start_date]}〜#{params[:end_date]}】の買い物リストを削除しました"
            redirect_to shopping_shopping_top_path
        end
    end

    def destroy_shopping
        destroy_shopping = Shopping.find_by(id: params[:id]).destroy
        if destroy_shopping
            flash[:notice] = "買い物リストの【　#{Food.find_by(id:destroy_shopping.food_id)[:name]}　】を削除しました"
            redirect_to shopping_edit_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date])
        end
    end

    def add_shopping
        @amount = params[:amount]
        @temporary_food_id = params[:food_id]
        if @temporary_food_id.nil?||@amount.empty? 
            redirect_to shopping_edit_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date]),flash:{alert: '食材の選択または数量の入力がされていません。選択及び入力をしてください。'}
        else
            quantity_conversion_branch
            shopping_item= Shopping.new(
                start_date: params[:start_date],
                end_date: params[:end_date],
                food_id: params[:food_id],
                quantity: @quantity ,
                unit: Food.find_by(id:params[:food_id])[:unit]
                )
            shopping_item.save
            flash[:notice]="#{params[:start_date]}~#{params[:end_date]}の買い物リストを追加しました"
            redirect_to shopping_edit_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date])
        end
    end
    
    def create_csv
        shopping_food = Shopping.where(start_date: params[:start_date],end_date:params[:end_date],food_id:15..181).order("food_id")
        shopping_seasoning = Shopping.where(start_date: params[:start_date],end_date:params[:end_date],food_id:182..224).order("food_id")
        csv_shopping_list = shopping_food + shopping_seasoning
            respond_to do |format|
                format.html
                format.csv do |csv|
                    send_csv_shopping_list(csv_shopping_list)
                end
            end
    end

    def send_csv_shopping_list(csv_shopping_list)
        csv_data = CSV.generate do |csv|
            column_names = %w(名前,,)
            csv << column_names
            csv_shopping_list.each do |item|
                if item.unit != "none"
                    column_values = [
                        Food.find_by(id:item.food_id)[:name],
                        item.quantity,
                        item.unit
                        ]
                else
                    column_values = [
                        Food.find_by(id:item.food_id)[:name],
                        "",
                        ""
                        ]
                end
                csv << column_values
            end
        end
        send_data(csv_data, filename: "買い物リスト.csv")
    end

end


    

app/helpers/shopping_helper.rb
module ShoppingHelper

    def menus
        menu.all
    end

    def shopping_all
        Shopping.all 
    end

    def shopping_list
        Shopping.where(start_date: params[:start_date],end_date:params[:end_date],food_id:15..181).order("food_id")
        #food_idを昇順
    end

    def shopping_seasoning
        Shopping.where(start_date: params[:start_date],end_date:params[:end_date],food_id:182..224).order("food_id")
    end
end

app/views/shopping/create_shopping_list.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shopping</title>
</head>
<body>
    <div class="input_table_2">
        <div class="input_table_title">買い物リスト作成<%= link_to shopping_shopping_top_path,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
        <div class='central_part'>
            <div class="description">日付を選択してください。</div>
                <div class="form-error"><%= flash[:error_new_shopping] %></div>
            <div class="form_shopping_list">
                <%= form_with url:"/shopping/sum_shopping_list" do |f| %>
                    <%= f.date_field :start_date ,class:"shopping_select_date"%> 〜 <%= f.date_field :start_date2,class:"shopping_select_date"%>
                    <%= f.button :type => "submit",class:"create_shoppinglist_btn" do %><i class="fas fa-folder-plus"></i><% end %>
                <% end %>
            </div>
            <div class="menu_calendar_shopping_list_creation">
                <%= week_calendar number_of_weeks:2,events:@menus do |date,menus| %>
                    <%= date.day %>
                    <% menus.each do |m| %>
                        <div>
                            <li><%= link_to Recipe.find_by(id:m.recipe_id).name,Recipe.find_by(id:m.recipe_id).address,class:"recipe_link" %></li>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</body>
</html>

app/views/shopping/edit_shopping_list.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shopping List</title>
</head>
<body>
    <div class="input_table_2">
        <div class="input_table_title">買い物リスト編集<%= link_to shopping_show_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date]),class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
        <section>
            <div class="edit_sub_title"><%= params[:start_date]%>〜<%=params[:end_date]%></div>
            <%= link_to shopping_list_delete_path(start_date:params[:start_date],end_date:params[:end_date]), method: :delete, data: { confirm: "買い物リストのすべての項目を削除します。削除してよろしいですか?"} ,class:"shopping_list_btn" do%><i class="fa-solid fa-trash-can"> 買い物リスト削除</i><%end%>
            <div class="form-error"><%= flash[:error_edit_shopping] %></div>
            <table class="edit_shopping_list_form">
                <tr>
                    <th></th>
                    <th>食材名</th>
                    <th></th>
                    <th></th>
                </tr>
                <%shopping_list().each do |item|%>
                    <tr>
                        <td>
                            <%= form_with url:"/shopping/#{item.id}/delete",method: :delete do |f1|%>
                                <%= f1.hidden_field :start_date, value: params[:start_date] %>
                                <%= f1.hidden_field :end_date, value: params[:end_date] %>
                                <%= f1.button type:"submit", class:"edit_form_btn", data: { confirm: "削除してよろしいですか?"} do%><i class="far fa-trash-alt"></i><%end%>
                            <%end%>
                        </td>
                        <td>
                            <%= Food.find_by(id:item.food_id)[:name]%>
                        </td>
                        <% if item.unit != "none"%>
                            <%= form_with url:"/shopping/update_shopping_list" do |f2| %>
                                <td>
                                    <%= f2.hidden_field :id, value: item.id %>
                                    <%= f2.hidden_field :start_date, value: params[:start_date] %>
                                    <%= f2.hidden_field :end_date, value: params[:end_date] %>
                                    <%= f2.text_field :quantity,value:item.quantity,size:10,class:"shopping_amount_form"%>　<%= item.unit%>
                                </td>
                                <td>
                                    <%= f2.button type:"submit", class:"edit_form_btn" do%><i class="fas fa-edit"></i><%end%>
                                </td>
                            <%end%>
                        <%end%>
                    </tr>
                <%end%>
                <%shopping_seasoning().each do |item|%>
                    <tr>
                        <td class='shopping_seasonings'>
                            <%= form_with url:"/shopping/#{item.id}/delete",method: :delete do |f3|%>
                                <%= f3.hidden_field :start_date, value: params[:start_date] %>
                                <%= f3.hidden_field :end_date, value: params[:end_date] %>
                                <%= f3.button type:"submit",class:"edit_form_btn" , data: { confirm: "削除してよろしいですか?"} do%><i class="far fa-trash-alt"></i><%end%>
                            <%end%>
                        </td>
                        <td>
                            <%= Food.find_by(id:item.food_id)[:name]%>
                        </td>
                    </tr>
                <%end%>
            </table>
            <br>
            <div class="edit_sub_title"><i class="fa-solid fa-cart-plus"></i>　買い物リストの追加</div>
                <div class="form-error"><%= flash[:alert] %></div>
                <%=form_with url:"/shopping/add_shopping", id:"add_form" do |f| %>
                    <%= f.hidden_field :start_date, value: params[:start_date] %>
                    <%= f.hidden_field :end_date, value: params[:end_date] %>
                <table class="add_shoppinglist">
                    <tr>
                        <td>
                            <div class="form-input-select"> 
                                <%= f.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id:'parent_category'}%>
                            </div>
                        </td>
                        <td>    
                            <div class ="listing-product-detail__category"></div>
                        </td>
                    </tr>
                </table>
                    <%= f.text_field :amount ,class:"add_shopping_amount_form"%>
                    <%= f.button type:"submit",class:"shopping_list_btn" do%><i class="fa-solid fa-circle-plus"></i> 追加<%end%>
                <%end%>
            <br>
        </section>
    </div>
</body>
</html>

app/views/shopping/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shopping index</title>
</head>
<body>
    <nav>
        <div class="nav_title">Shopping</div>
            <div class="nav_menu">
                <li><%= link_to("買い物リスト作成","/shopping/create_shopping_list",class:"nav_menu_link")%></li>
            </div>
    </nav>
    <article>
        <div class="check_shopping_list">
            <div class="index_description">確認したい買い物リストの日付を選択してください。</div>
            <div class="form-error"><%=flash[:error_view]%></div>   
                <div class="shoppinglist_date">
                    <%= form_with url:"/shopping/search" do |f| %>
                        <%= f.date_field :start_date,class:"shopping_select_date"%> 〜 <%= f.date_field :end_date,class:"shopping_select_date" %>
                        <%= f.button :type => "submit",class:"shopping_search_btn" do %><i class="fas fa-search"></i><% end %>
                    <% end %>
                </div>
        </div>
        <!--献立カレンダー-->
        <div class="menu_calender">
            <%= week_calendar number_of_weeks:2 ,events:@menus do |date,menus| %>
                <%= date.day %>
                <% menus.each do |m| %>
                    <div>
                        <li><%= link_to Recipe.find_by(id:m.recipe_id).name,Recipe.find_by(id:m.recipe_id).address ,class:"calender_recipe_name"%></li>
                    </div>
                <% end %>
            <% end %>
        </div>
    </article>
</body>
</html>

app/views/shopping/shopping_top.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shopping index</title>
</head>
<body>
  <header>
    <div class="title_logo">Menutable</div>
      <div class="account_list">
        <%= link_to "/users/#{@current_user.id}",class:'header_link',method: :get do %>
          <i class="fas fa-user"></i> <%=@current_user.login_id%>
        <%end%>
        <%= link_to "/users/logout",class:'header_link',method: :post, data: {confirm: "ログアウトしますか？"} do %>
          <i class="fas fa-sign-out-alt"></i> Logout
        <%end%>
      </div>
      <div class="menu_list">
        <%= link_to "/about",class:'header_link',method: :get do %>
          <i class="fas fa-home"></i> About
        <%end%>
        <%= link_to "/recipes/recipe_top",class:'header_link',method: :get do %>
          <i class="fas fa-book"></i> Recipe
        <%end%>
        <%= link_to "/meal/menu_top",class:'header_link',method: :get do %>
          <i class="far fa-calendar-alt"></i> Menu
        <%end%>
        <%= link_to "/shopping/shopping_top",class:'header_link',method: :get do %>
          <i class="far fa-list-alt"></i> Shopping
        <%end%>
        <%= link_to 'https://www.iy-net.jp/',target: :_blank, rel: "noopener noreferrer",class:'header_link',method: :get do %>
          <i class="fas fa-shopping-cart"></i> Store
        <%end%>
      </div>
  </header>
  <main>
    <div class="auto">
      <% if flash[:notice] %>
        <div class="flash"><%= flash[:notice] %></div>
      <%end%>
    </div>
    <nav>
        <div class="nav_title">Shopping</div>
            <div class="nav_menu">
                <li><%= link_to("買い物リスト作成","/shopping/create_shopping_list",class:"nav_menu_link")%></li>
            </div>
    </nav>
    <article>
        <div class="check_shopping_list">
            <div class="index_description">確認したい買い物リストの日付を選択してください。</div>
            <div class="form-error"><%=flash[:error_view]%></div>   
                <div class="shoppinglist_date">
                    <%= form_with url:"/shopping/search_shopping" do |f| %>
                        <%= f.date_field :start_date,class:"shopping_select_date"%> 〜 <%= f.date_field :end_date,class:"shopping_select_date" %>
                        <%= f.button :type => "submit",class:"shopping_search_btn" do %><i class="fas fa-search"></i><% end %>
                    <% end %>
                </div>
        </div>
        <!--献立カレンダー-->
        <div class="menu_calender">
            <%= week_calendar number_of_weeks:2 ,events:@menus do |date,menus| %>
                <%= date.day %>
                <% menus.each do |m| %>
                    <div>
                        <li><%= link_to Recipe.find_by(id:m.recipe_id).name,Recipe.find_by(id:m.recipe_id).address ,class:"calender_recipe_name"%></li>
                    </div>
                <% end %>
            <% end %>
        </div>
    </article>
  </main>
</body>
</html>

app/views/shopping/show_shopping_list.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shopping List</title>
</head>
<body>
    <header>
      <div class="title_logo">Menutable</div>
        <div class="account_list">
          <%= link_to "/users/#{@current_user.id}",class:'header_link',method: :get do %>
            <i class="fas fa-user"></i> <%=@current_user.login_id%>
          <%end%>
          <%= link_to "/users/logout",class:'header_link',method: :post, data: {confirm: "ログアウトしますか？"} do %>
            <i class="fas fa-sign-out-alt"></i> Logout
          <%end%>
        </div>
        <div class="menu_list">
          <%= link_to "/about",class:'header_link',method: :get do %>
            <i class="fas fa-home"></i> About
          <%end%>
          <%= link_to "/recipes/recipe_top",class:'header_link',method: :get do %>
            <i class="fas fa-book"></i> Recipe
          <%end%>
          <%= link_to "/meal/menu_top",class:'header_link',method: :get do %>
            <i class="far fa-calendar-alt"></i> Menu
          <%end%>
          <%= link_to "/shopping/shopping_top",class:'header_link',method: :get do %>
            <i class="far fa-list-alt"></i> Shopping
          <%end%>
          <%= link_to 'https://www.iy-net.jp/',target: :_blank, rel: "noopener noreferrer",class:'header_link',method: :get do %>
            <i class="fas fa-shopping-cart"></i> Store
          <%end%>
        </div>
    </header>
    <main>
      <div class="auto">
        <% if flash[:notice] %>
          <div class="flash"><%= flash[:notice] %></div>
        <%end%>
      </div>
      <nav>
          <div class="nav_title">Shopping</div>
          <div class="nav_menu">
              <li><%= link_to("買い物リスト作成",shopping_create_shopping_list_path,class:"nav_menu_link")%></li>
              <li><%= link_to("買い物リスト検索",shopping_shopping_top_path,class:"nav_menu_link")%></li>
          </div>
      </nav>
      <article>
          <div class="show_shopping_list">
              <div class="sub_title_shopping_list"><i class="fas fa-tasks"></i>　<%= params[:start_date]%>　〜　<%=params[:end_date]%></div>
                  <div class="setting">
                      <ul class="shopping_list_settings">
                          <li><%= link_to "#" do%><i class="fas fa-wrench"></i> Setting<%end%>
                              <ul>
                                  <li><%= link_to edit_shopping_list_path(start_date:params[:start_date],end_date:params[:end_date]) do%>編集/削除<%end%></li>
                                  <li><%= link_to create_csv_path(format: :csv,start_date:params[:start_date],end_date:params[:end_date]) do %><i class="fas fa-file-csv"></i> CSV出力<% end %></li>                               
                              </ul>
                          </li>
                      </ul>
                  </div>
              <table class="shopping_list">
                  <tr>
                      <th> </th>
                      <th>食材</th>
                      <th> </th>
                  </tr>
                  <%shopping_list().each do |item|%>
                      <tr>
                          <td>
                              <%= check_box_tag :check1 ,class:"check_box"%>
                          </td>
                          <td>
                              <%=Food.find_by(id:item.food_id)[:name]%>
                          </td>
                          <% if item.unit != "none"%>
                          <td>
                              <%= item.quantity%><%= item.unit%>
                          </td>
                          <%end%>
                      </tr>
                  <%end%>
                      <tr>
                          <th> </th>
                          <th>
                              調味料
                          </th>
                      </tr>
                  <%shopping_seasoning().each do |item|%>
                      <tr>
                          <td>
                              <%= check_box_tag :check1%>
                          </td>
                          <td>
                              <%=Food.find_by(id:item.food_id)[:name]%>
                          </td>
                      </tr>
                  <%end%>
              </table>
          </div>
      </article>
    </main>
</body>
</html>