config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'recipes/get_category_children' => 'recipes#get_category_children', defaults: { format: 'json' } #Ajaxで動くアクションのルートを作成
  get 'shopping/get_category_children' => 'shopping#get_category_children', defaults: { format: 'json' } #Ajaxで動くアクションのルートを作成

  get "/" => "home#index"
  get "/about" => "home#about"
  get "/unauthenticated" => "home#unauthenticated"
  #アカウント
  get "users/login_form" => "user#login_form" 
  post "users/login" => "user#login" 
  get "users/new_account" => "user#new_account" 
  post "users/create_account" => "user#create_account"
  post "users/logout" => "user#logout"
  get "users/:id" => "user#show"
  delete "users/delete" => "user#destroy_account"
  get "users/:id/edit" => "user#edit_account"
  post "/update_account" => "user#update_account"
  #レシピ機能
  get "recipes/recipe_top" => "recipes#recipe_top" #レシピ一覧
  get "recipes/recipe_search" => "recipes#search_recipe" #レシピ検索
  get "recipes/recipe_new" => "recipes#recipe_new" #レシピ登録ページ
  post "recipes/create_recipe" => "recipes#create_recipe" #レシピ登録
  get "recipes/show_food_choices/:id" => "recipes#show_food_choices" #材料リストの設定(自動検索)
  get "recipes/show_food_choices_by_category/" => "recipes#show_food_choices_by_category" #材料リストの追加設定（手動）
  post "recipes/create_materials" => "recipes#create_materials" #材料リストの登録
  post "recipes/create_manual_materials" => "recipes#create_manual_materials" #材料リストの追加登録
  get "recipes/:id" => "recipes#show" #レシピと材料リストの詳細
  delete "recipes/:id/delete" => "recipes#destroy_recipe" #レシピ削除
  get "recipes/:id/edit_recipe" => "recipes#edit_recipe" #レシピ編集
  post "recipes/:id/update_recipe" => "recipes#update_recipe" #レシピ更新
  delete "recipes/material/:id/delete" => "recipes#destroy_material" #材料リストの削除
  get "recipes/:id/edit_material" => "recipes#edit_material" #材料リストの編集
  post "recipes/:id/update_material" => "recipes#update_material" #材料リストの更新
  #献立機能
  get "meal/menu_top" => "meal#menu_top" #献立表示
  get "meal/menu_new" => "meal#menu_new" #献立決め
  get "meal/menu_search" => "meal#menu_search" #献立用レシピ検索
  post "meal/menu_select" => "meal#menu_select" #献立用レシピ選択
  delete "meal/menu_delete" => "meal#destroy_menu" #献立削除
  #買い物リスト
  get "shopping/shopping_top" => "shopping#shopping_top" #買い物リスト
  post "shopping/search_shopping" => "shopping#search_shopping" #買い物リストの期間を指定する
  get "shopping/create_shopping_list" => "shopping#create_shopping_list" #買い物リスト作成画面
  post "shopping/sum_shopping_list" => "shopping#sum_shopping_list" #買い物リストの作成
  delete "shopping/list/delete" => "shopping#destroy" #買い物リストの削除
  get "shopping/show_shopping_list" => "shopping#show_shopping_list"#買い物リストを表示画面
  get "edit_shopping_list" => "shopping#edit_shopping_list" #買い物リスト編集画面
  post "update_shopping_list" => "shopping#update_shopping_list" #買い物リスト変更
  post "add_shopping" => "shopping#add_shopping"  #買い物リストの追加
  delete "shopping/:id/delete" => "shopping#destroy_shopping" #買い物リストの項目削除
  get "create_csv" => "shopping#create_csv" #買い物リストのCSVを作成
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: { message: 'は1文字以上入力してください。' }
    validates :keyword ,format:{with:/\A[ぁ-んァ-ン一-龥]/, message: 'は全角ひらがな、全角カタカナ、漢字で入力してください'}
    validates :address ,presence:{ message: 'は必須項目です。入力して下さい。' }
end

app/controllers/recipes_controller.rb
require "csv"
require_relative "converter.rb"
class RecipesController < ApplicationController
include Converter
    def recipe_top
    end

    def search_recipe
        @search_recipe = Recipe.where('name LIKE ?', "%#{params[:searchword]}%")
        render action: :index
    end

    def recipe_new
    end

    def create_recipe
        @url = params[:address] 
            if @url.include?("https://")
                html = URI.open(@url).read
                doc = Nokogiri::HTML.parse(html)
                doc_name = doc.css('.name')
                doc_amount = doc.css('.amount')
                @created_recipe = Recipe.new(
                        name: doc.title,
                        keyword: "不明",
                        address: params[:address]
                        )   
                    if @created_recipe.save
                        doc_name.zip(doc_amount) do |n,a|
                            @created_ingredient = Ingredient.new(
                                foodname: n.text.delete("■,●,◎,○,\n, ,★,☆"),
                                amount: a.text.delete("■,●,◎,○,\n, ,★,☆"),
                                recipe_id: @created_recipe.id
                                )
                            @created_ingredient.save
                        end
                        redirect_to action: :show_food_choices, id: @created_recipe.id
                    else
                        @url_error = "URLを再度確認してください。"
                        render action: :recipe_new
                    end
            else
                @url_error = "URLを入力してください。"
                render action: :recipe_new
            end
    end

    def show_food_choices
        @ingredients= Ingredient.where(recipe_id: params[:id])
        @automaticsearch_ingredients = []
        @ingredients.each do |m|
            @food=Food.where("name LIKE ? OR keyword LIKE ?","%#{m.foodname}%","%#{m.foodname}%")
                unless @food.blank?
                    @automaticsearch_ingredients << m.amount    #foodテーブルに該当するもの
                end
        end
        @registered_material = Material.where(recipe_id: params[:id]) 
        @category_parent_array = ["-- category --"]
        #データベースから、親カテゴリーのみ抽出し、配列化
            Food.where(unit:nil).each do |parent|
                @category_parent_array << parent.name
            end
    end

    def get_category_children
        #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
        @category_children = Food.find_by(name: params[:category]).children
    end
    
    def create_materials #materialレコードの作成
        @recipe_id = params[:recipe_id]
        food_ids = params[:food_ids]
        amounts = params[:amounts].split
        if amounts.count === food_ids.count
            food_ids.zip(amounts) do |food_id,amount| 
                @temporary_food_id = food_id
                @amount = amount
                
                quantity_conversion_branch
                
                @created_material = Material.create(
                    recipe_id: @recipe_id,
                    food_id:  @temporary_food_id,
                    quantity: @quantity
                    )
            end        
            flash[:notice]="材料登録しました"
            redirect_to "/recipes/show_food_choices/#{params[:recipe_id]}/"
        else
            flash[:error_create_materials] = "各材料１つ、チェックボックスを選択してください。"
            redirect_to "/recipes/show_food_choices/#{params[:recipe_id]}/"
        end       
    end

    def create_manual_materials
        @temporary_food_id = params[:food_id]
        @amount = params[:amount]
        case params[:kind]
        when "edit_material" then
            if  @temporary_food_id.nil?||@amount.empty? 
                redirect_to "/recipes/#{params[:recipe_id]}/edit_material",flash:{alert: '食材の選択または数量の入力がされていません。選択及び入力をしてください。'}
            else
                quantity_conversion_branch
                @created_material = Material.create(
                    recipe_id: params[:recipe_id],
                    food_id:  @temporary_food_id,
                    quantity: @quantity
                    )
                flash[:notice]="新しく「　#{Food.find_by(id:@temporary_food_id).name}　」を登録しました"
                redirect_to "/recipes/#{params[:recipe_id]}/edit_material"
            end    
        when "new_material" then
            if  @temporary_food_id.nil? ||@amount.empty? 
                redirect_to "/recipes/show_food_choices/#{params[:recipe_id]}" ,flash:{alert: '食材の選択または数量の入力がされていません。選択及び入力をしてください。'}
            else
                quantity_conversion_branch
                @created_material = Material.create(
                    recipe_id: params[:recipe_id],
                    food_id:  @temporary_food_id,
                    quantity: @quantity
                    )
                flash[:notice]="「　#{Food.find_by(id:@temporary_food_id).name}　」を登録しました"
                redirect_to "/recipes/show_food_choices/#{params[:recipe_id]}/"
            end
        end
    end

    def show
    end

    def destroy_recipe
        destroy_recipe = Recipe.find_by(id: params[:id]).destroy
        if destroy_recipe
            flash[:notice] = "レシピを削除しました"
            destroy_ingredients = Ingredient.where(recipe_id: params[:id]).destroy_all
            destroy_materials = Material.where(recipe_id: params[:id]).destroy_all
            redirect_to("/recipes/recipe_top")
        end
    end

    def edit_recipe
    end

    def update_recipe
        @edit_recipe = Recipe.find_by(id: params[:id])
        @edit_recipe.name = params[:name]
        @edit_recipe.keyword = params[:keyword]
        @edit_recipe.address = params[:address]
        if @edit_recipe.save
            flash[:notice]= "変更しました"
            redirect_to("/recipes/#{params[:id]}")
        else
            render"recipes/edit_recipe"
        end
    end

    def destroy_material
        destroy_material = Material.find_by(id: params[:id]).destroy
        if destroy_material
            flash[:notice] = "削除しました"
            redirect_to("/recipes/#{params[:recipe_id]}/edit_material")
        end
    end

    def edit_material
        @category_parent_array = ["---"]
        #データベースから、親カテゴリーのみ抽出し、配列化
            Food.where(unit:nil).each do |parent|
            @category_parent_array << parent.name
            end
    end

    def update_material
        edit_material = Material.find_by(id:params[:id]) 
        if params[:quantity].empty?
            redirect_to "/recipes/#{params[:recipe_id]}/edit_material",flash:{info: '数量が空欄です。再度入力してください。'}
        elsif params[:quantity]
            edit_material.quantity = params[:quantity]
            if edit_material.save
                flash[:notice]= "変更しました"
                redirect_to("/recipes/#{params[:recipe_id]}/edit_material")
            end
        end
    end
end

app/helpers/recipe_helper.rb
require 'open-uri'
require 'nokogiri'
require 'kconv'

module RecipeHelper
    def recipes 
        Recipe.all
    end

    def recipe 
        Recipe.find_by(id: params[:id])
    end

    def ingredients 
        Ingredient.where(recipe_id: params[:id])
    end

    def food_category 
        Food.find_by(id: @category_id.to_i)
    end

    def scraping
        recipe = Recipe.find_by(id: params[:id])
        url = recipe.address
        html = URI.open(url).read
        doc = Nokogiri::HTML.parse(html)
    end
end

app/helpers/recipes_helper.rb
require 'open-uri'
require 'nokogiri'
require 'kconv'

module RecipesHelper
    def recipes 
        Recipe.all
    end

    def recipe 
        Recipe.find_by(id: params[:id])
    end

    def ingredients 
        Ingredient.where(recipe_id: params[:id])
    end

    def materials
        Material.where(recipe_id: params[:id])
    end

    def scraping
        recipe = Recipe.find_by(id: params[:id])
        url = recipe.address
        html = URI.open(url).read
        doc = Nokogiri::HTML.parse(html)
    end
end

app/views/recipes/edit.html.erb
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Edit recipe</title>
    </head>
    <body>
        <div class="page_title"><h1>Edit recipe</h1></div>
        <br>
        <% if @edit_recipe %>
            <% @edit_recipe.errors.full_messages.each do |message| %>
                <div class="form-error">
                    <%= message %>
                </div>
            <% end %>
        <% end %>
        <br>
        <div class="update_recipe_form">
        <table>
            <%= form_with url:"/recipes/#{params[:id]}/update_recipe" do |f| %>
                <tr>
                    <td><%= f.label :"レシピ名"%></td>
                    <td><%= f.text_field :name ,:value=> recipe().name ,size:50 %></td>
                </tr>
                <tr>
                    <td><%= f.label :"keyword"%></td>
                    <td><%= f.text_field :keyword ,:value=> recipe().keyword ,size:50 %></td>
                </tr>
                <tr>
                    <td><%= f.label :"URL"%></td>
                    <td><%= f.text_field :address ,:value=> recipe().address ,size:50 %></td>
                </tr>
        </table>
        <br>
                    <%= f.submit "変更" ,class:"edit_submit_button"%>                
            <% end %>
        </div>
        <br>
        <br>
        <div class="btn_return">
            <%= link_to "戻る","/recipes/#{params[:id]}" %>
        </div>
    </body>
</html>

app/views/recipes/edit_material.erb
<html>
<head>
    <%= javascript_pack_tag 'application','data-turbolinks-track': 'reload'%>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Edit material</title>
</head>
<body>
    <div class="input_table_2">
        <div class="input_table_title">材料リスト編集<%= link_to "/recipes/#{params[:id]}" ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
        <section>
            <div class="main_contents">
            <div class="material_sub_title"><i class="fas fa-edit"></i> 材料リスト編集</div>
                <div class="form-error"><%= flash[:info] %></div>
                <table class="edit_material_form">
                    <tr>
                        <th></th>
                        <th>名前</th>
                        <th>数量</th>
                        <th> </th>
                        <th> </th>
                        
                    </tr>
                <% materials().each do |m|%>
                    <tr>
                        <td>
                            <%= form_with url:"/recipes/material/#{m.id}/delete",method: :delete do |f|%>
                                <%= f.hidden_field :recipe_id, value: params[:id]%>
                                <%= f.button type:"submit",class:"material_delete_btn", data: { confirm: "削除してよろしいですか?"} do%><i class="fa-regular fa-trash-can"></i><%end%>
                            <%end%>
                        </td>
                        <td>
                            <%= Food.find_by(id: m.food_id)[:name]%>
                        </td>
                        <%unless Food.find_by(id: m.food_id)[:unit] == "none"%>
                            <%= form_with url:"/recipes/#{m.id}/update_material" do |f2| %>
                                <td>
                                    <%= f2.hidden_field :recipe_id, value: params[:id] %>
                                    <%= f2.text_field :quantity, value:m.quantity.floor(1), size:10, class:"edit_material_input"%>
                                </td>
                                <td>
                                    <%= Food.find_by(id: m.food_id)[:unit]%>
                                </td>
                                <td>
                                    <%= f2.button type:"submit",class:"update_material_btn" do%><i class="fa-thin fa-pen-to-square"></i><%end%>
                                </td>
                            <%end%>
                        <%end%>
                    </tr>
                <%end%>
                </table>
            <div class="material_sub_title"><i class="fas fa-plus-square"></i> 材料の追加</div>
                <div class="form-error"><%= flash[:alert] %></div>
                <div class="edit_add_material">
                    <%=form_with url:"/recipes/create_manual_materials", id:"add_form" do |f| %>
                    <%= f.hidden_field :kind, value: "edit_material" %>
                    <%= f.hidden_field :recipe_id, value: params[:id] %>
                    <table>
                        <tr>
                            <td>
                                <div class="form-input-select"> 
                                    <%= f.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id:'parent_category'}%>
                                </div>
                            </td>
                            <td>
                                <div class ="listing-product-detail__category"></div>
                            </td>
                        </tr>
                        <tr>
                    </table>
                    分量：<%= f.text_field :amount ,class:"edit_add_material_input"%>
                    <%= f.submit "登録", class:"material_submit_btn"%>
                    <%end%>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

app/views/recipes/edit_recipe.html.erb
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Edit recipe</title>
</head>
<body>
    <div class="input_table">
        <div class="input_table_title">レシピ編集<%= link_to "/recipes/#{params[:id]}" ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
            <% if @edit_recipe %>
                <% @edit_recipe.errors.full_messages.each do |message| %>
                    <div class="form-error">
                        <%= message %>
                    </div>
                <% end %>
            <% end %>    
        <%= form_with url:"/recipes/#{params[:id]}/update_recipe" do |f| %>
            <table class="update_recipe_form">
                <tr>
                    <td>
                        <%= f.label :"Name",class:"update_recipe_label"%>
                    </td>
                    <td>
                        <%= f.text_field :name ,:value=> recipe().name ,size:50 ,class:"update_recipe_input"%>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%= f.label :"Keyword",class:"update_recipe_label"%>
                    </td>
                    <td>
                        <%= f.text_field :keyword ,:value=> recipe().keyword ,size:50,class:"update_recipe_input"%>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%= f.label :"URL",class:"update_recipe_label"%>
                    </td>
                    <td>
                        <%= f.text_field :address ,:value=> recipe().address ,size:50,class:"update_recipe_input"%>
                    </td>
                </tr>
            </table>      
            <%= f.button type:"submit",class:"recipes_submit_btn"%>
        <% end %>
    </div>
</body>
</html>

app/views/recipes/ingredient.html.erb
<!DOCTYPE html>
<html lang="ja">
<br>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>材料登録</title>
</head>
<body>
<div class="page_title">
    <h1>材料リストの登録</h1>
</div>
<table class="ingredient_1" border="1">
    <tr>
        <th>材料</th>
        <th>食材候補</th>
        <th>分量</th>
    </tr>
    <%= form_with url:"/recipes/create_materials" do |f| %>
        <%= f.hidden_field :recipe_id, value: params[:id] %>
        <%= @automaticsearch_ingredient %>
        <%@ingredients.each do |i|%>
            <% @foodlist = Food.where("name LIKE ? OR keyword LIKE ?","%#{i.foodname}%","%#{i.foodname}%")%>
            <%unless @foodlist.blank?%>
            <tr>
                <td>
                    <%= i.foodname%>
                </td>
                <td>
                    <%= f.collection_check_boxes :food_ids, @foodlist, :id, :name, include_hidden:false, multiple: true %>
                </td>
                <td>
                    <%= i.amount%>
                </td>
            </tr>
            <%end%>
        <%end%>
        <tr>
            <td></td>
            <td></td>
            <td>
                <%= f.hidden_field :amounts, value: @automaticsearch_ingredients%>
                <%= f.submit '登録' %>
            </td>
        </tr>
    <%end%>
</table> 
<br>
<h3 class="materials_not_on_the_list">その他の食材</h3>
<table class="ingredient_2" border="1">
    <tr>
        <th>材料</th>
        <th>分量</th>
    </tr>
    <%@ingredients.each do |i|%>
        <% @foodlist = Food.where("name LIKE ? OR keyword LIKE ?","%#{i.foodname}%","%#{i.foodname}%")%>
        <%if @foodlist.blank?%>
            <tr>
                <td><%= i.foodname%></td>
                <td><%= i.amount%></td>
            </tr>
        <%end%>
    <%end%>
</table>
<h4><%= link_to "上記の材料を材料リストに加えますか？", recipes_show_food_choices_by_category_path(id:params[:id])%></h4>
<br>

app/views/recipes/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>レシピ登録</title>
</head>
<body>
    <div class="input_table">
        <div class="input_table_title">Add Recipe<%= link_to recipes_index_path ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div> 
        <div class="create_recipe_attention">cookpadのみ対応</div>
        <% if @url_error %>
            <div class="form-error"><%= @url_error%></div>
        <%end%>    
        <div class="create_recipe_form">
            <%= form_with url:"/recipes/create_recipe" do |f| %>
                <%= f.label 'URL' ,class:"recipe_label"%>　
                <%= f.text_field :address ,class:"create_recipe_input"%>
                <%= f.button type:"submit", class:"recipes_submit_btn" do %><i class="fas fa-folder-plus"></i> Add<%end%>
            <%end%>
        </div>
    </div>
</body>
</html>

app/views/recipes/recipe_new.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>レシピ登録</title>
</head>
<body>
    <div class="input_table">
        <div class="input_table_title">レシピ登録<%= link_to recipes_recipe_top_path ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div> 
        <div class="create_recipe_attention">cookpadのみ対応</div>
        <% if @url_error %>
            <div class="form-error"><%= @url_error%></div>
        <%end%>    
        <div class="create_recipe_form">
            <%= form_with url:"/recipes/create_recipe" do |f| %>
                <%= f.label 'URL' ,class:"recipe_label"%>　
                <%= f.text_field :address ,class:"create_recipe_input"%>
                <%= f.button type:"submit", class:"recipes_submit_btn" do %><i class="fas fa-folder-plus"></i> Add<%end%>
            <%end%>
        </div>
    </div>
</body>
</html>

app/views/recipes/show_food_choices.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>材料登録</title>
</head>
<body>
    <div class="input_table_2">
        <div class="input_table_title">買い物リスト作成<%= link_to recipes_recipe_top_path ,class:"close_btn" do %><i class="fa-regular fa-circle-xmark"></i><%end%></div>
        <section>
        <div class="auto">
            <% if flash[:notice] %>
                <div class="flash"><%= flash[:notice] %></div>
            <%end%>
        </div>
            <div class="p_explanation">候補から各食材１つを選択してください</div>
            <div class="form-error"><%= flash[:error_create_materials] %></div>
                <%= form_with url:"/recipes/create_materials" do |f| %>
                    <table class="ingredients_list">
                        <tr>
                            <th>材料名</th>
                            <th>候補</th>
                            <th>分量</th>
                        </tr>
                    <%= @automaticsearch_ingredient %>
                    <% @ingredients.each do |i|%>
                    <% @foodlist = Food.where("name LIKE ? OR keyword LIKE ?","%#{i.foodname}%","%#{i.foodname}%")%>
                        <%unless @foodlist.blank?%>
                        <tr>
                            <td>
                                <div class="foodname"><%= i.foodname%></div>
                            </td>
                            <td>
                                <%= f.collection_check_boxes :food_ids, @foodlist, :id, :name, include_hidden:false, multiple: true %>
                            </td>
                            <td>
                                <%= i.amount%>
                            </td>
                        </tr>
                        <%end%>
                    <%end%>
                    </table>
                    <%= f.hidden_field :recipe_id, value: params[:id] %>
                    <%= f.hidden_field :amounts, value: @automaticsearch_ingredients%>
                    <%= f.button type:"submit",class:"material_submit_btn" do %><i class="fas fa-folder-plus"></i> Add<%end%>
                <%end%>
                <div class="p_explanation">以下は選択候補が絞れなかった食材です。<br>カテゴリー選択し該当する食材を登録してください</div>
                <table class="ingredients_list">
                    <tr>
                        <th>材料名</th>
                        <th>分量</th>
                    </tr>
                    <% @ingredients.each do |m|%>
                    <% @foodlist = Food.where("name LIKE ? OR keyword LIKE ?","%#{m.foodname}%","%#{m.foodname}%")%>
                        <%if @foodlist.empty?%>
                            <tr>
                                <td><%= m.foodname%></td>
                                <td><%= m.amount%></td>
                            </tr>
                        <%end%>
                    <%end%>
                </table>
            <!-- 材料リストの追加 -->
            <div class="form-error"><%= flash[:alert] %></div>
                <div class="add_material">
                <%=form_with url:"/recipes/create_manual_materials", id:"add_form",class:"add_form" do |f| %>
                    <table class="add_material_table">
                    <tr>
                        <td><%= f.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id:'parent_category'}%></td>
                        <td><div class ="listing-product-detail__category"></div></td>
                    </tr>
                    </table>
                    <div class="material_amount_form">
                        分量：<%= f.text_field :amount, size:20, class:"amount_form"%></td>
                    </div>
                    <%= f.hidden_field :kind, value: "new_material" %>
                    <%= f.hidden_field :recipe_id, value: params[:id] %>
                    <%= f.button type:"submit",class:"material_submit_btn", onclick:'add()' do %><i class="fas fa-folder-plus"></i> Add<%end%>
                <%end%>
                </div>
            <%= link_to "/recipes/#{params[:id]}",class:"recipe_show_link" do %>登録終了<%end%>
            </div>
        </section>
</body>
</html>